# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x04game\"<\n\x13\x43reateOrJoinRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x0frequest_players\x18\x02 \x01(\x05\"^\n\x14\x43reateOrJoinResponse\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x1c\n\x14total_players_needed\x18\x02 \x01(\x05\x12\x15\n\rplayer_joined\x18\x03 \x01(\x08\" \n\x0bWaitRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\"l\n\x0cWaitResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x17\n\x0f\x63urrent_players\x18\x02 \x01(\x05\x12\x1c\n\x14total_players_needed\x18\x03 \x01(\x05\x12\x14\n\x0cgame_started\x18\x04 \x01(\x08\" \n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"X\n\x11GameUpdateRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12 \n\x08position\x18\x02 \x01(\x0b\x32\x0e.game.Position\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\"E\n\x0ePlayerPosition\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12 \n\x08position\x18\x02 \x01(\x0b\x32\x0e.game.Position\"g\n\x12GameUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12/\n\x11players_positions\x18\x03 \x03(\x0b\x32\x14.game.PlayerPosition2\xda\x01\n\x0bGameService\x12I\n\x10\x43reateOrJoinGame\x12\x19.game.CreateOrJoinRequest\x1a\x1a.game.CreateOrJoinResponse\x12;\n\x10WaitForGameStart\x12\x11.game.WaitRequest\x1a\x12.game.WaitResponse0\x01\x12\x43\n\nGameUpdate\x12\x17.game.GameUpdateRequest\x1a\x18.game.GameUpdateResponse(\x01\x30\x01\x42\tZ\x07/protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007/protos'
  _globals['_CREATEORJOINREQUEST']._serialized_start=20
  _globals['_CREATEORJOINREQUEST']._serialized_end=80
  _globals['_CREATEORJOINRESPONSE']._serialized_start=82
  _globals['_CREATEORJOINRESPONSE']._serialized_end=176
  _globals['_WAITREQUEST']._serialized_start=178
  _globals['_WAITREQUEST']._serialized_end=210
  _globals['_WAITRESPONSE']._serialized_start=212
  _globals['_WAITRESPONSE']._serialized_end=320
  _globals['_POSITION']._serialized_start=322
  _globals['_POSITION']._serialized_end=354
  _globals['_GAMEUPDATEREQUEST']._serialized_start=356
  _globals['_GAMEUPDATEREQUEST']._serialized_end=444
  _globals['_PLAYERPOSITION']._serialized_start=446
  _globals['_PLAYERPOSITION']._serialized_end=515
  _globals['_GAMEUPDATERESPONSE']._serialized_start=517
  _globals['_GAMEUPDATERESPONSE']._serialized_end=620
  _globals['_GAMESERVICE']._serialized_start=623
  _globals['_GAMESERVICE']._serialized_end=841
# @@protoc_insertion_point(module_scope)
